### ISSUE TITLE
bgpalerter image - can't find and run /bin/sh though works via plain chroot

### ISSUE THREAD

**Issue by knan-md** [michael-yuji/xc#6]
Hi!

I was just fooling around with xc now, after seeing it at eurobsdcon in Coimbra - cool talk and good demo this year :)

So I did an `xc pull nttgin/bgpalerter:v1.32.0` to fool around with that image, since that's something that could be of use to us. Downloads fine, but when I try to run it via `xc run nttgin/bgpalerter:v1.32.0 --name bgpalerter /bin/sh` I get `xc: Container faulted ExecutableNotFound.`

/bin/sh in the image is a symlink to a dynamic musl libc /bin/busybox.

When I do a chroot to the downloaded image on the host - `chroot /zroot/xc/datasets/sha256:c1b2ad122787b74af9f722f2fb61ea563bfb90ffe70572a5c04d959d9ffe824e/ /bin/sh` - I can run the /bin/sh just fine, which is confusing.

I know my xc works fine with the example mariadb image and freebsdxc image from the quickstart document.

Hints about what I'm doing wrong? :)

**Comment by bsdxc** [comment]
This is could be bug in `xcd` trying to check if an executable exists

**Comment by elliptic-kitty** [comment]
This is probably a bug in xcd

**Comment by elliptic-kitty** [comment]
@knan-md can you c if https://github.com/elliptic-kitty/xc/tree/symlink_fix solve ur problem?

**Comment by knan-md** [comment]
@elliptic-kitty great, yes, that got me as far as running /bin/sh in the container at least. Thanks! (Now to see if anything more will run)
